import { addUser, as, asService, createDb, denied, eq, ok, summary } from './harness.mjs'

const db = await createDb({ quiet: true })
const one = async (sql, p) => Object.values((await db.query(sql, p)).rows[0] ?? {})[0]

console.log('\n# Encryption')
{
  const c = await one(`select private.enc('9876543210')`)
  ok(c instanceof Uint8Array && c.length > 20, 'enc() returns ciphertext bytes')
  ok(!Buffer.from(c).toString('latin1').includes('9876543210'), 'ciphertext does not contain the plaintext')
  eq(c[0], 1, 'first byte is the key version')
  eq(await one(`select private.dec(private.enc('9876543210'))`), '9876543210', 'dec(enc(x)) = x')
  eq(await one(`select private.dec(private.enc('नमस्ते ₹85L'))`), 'नमस्ते ₹85L', 'round-trips unicode')
  ok((await one(`select private.enc('a') <> private.enc('a')`)) === true, 'same input encrypts differently each time')
  eq(await one(`select private.enc('')`), null, 'empty string -> null')
  eq(await one(`select private.dec_num(private.enc_num(8500000.50))`), '8500000.50', 'numeric round-trip')
  eq(await one(`select private.bidx('9876543210') = private.bidx('9876543210')`), true, 'blind index is deterministic')
  eq(await one(`select length(private.bidx('9876543210'))`), 64, 'blind index is 64 hex chars')
  eq(await one(`select public.normalize_phone('+91 98765-43210')`), '9876543210', 'normalize_phone strips +91 and symbols')
  eq(await one(`select public.normalize_phone('098765 43210')`), '9876543210', 'normalize_phone strips leading 0')
  eq(await one(`select public.phone_hint('9876543210')`), '98••••••10', 'phone_hint masks the middle')
  await denied(db.query(`select private.dec('\\x01ffff'::bytea)`), 'tampered ciphertext is rejected')
}

console.log('\n# Users')
const owner = await addUser(db, { username: 'owner', role: 'owner' })
const admin = await addUser(db, { username: 'admin1', role: 'admin' })
const mgr = await addUser(db, { username: 'manager1', role: 'manager', manager: owner })
const sales = await addUser(db, { username: 'sales1', role: 'sales', manager: mgr })
const sales2 = await addUser(db, { username: 'sales2', role: 'sales' })
const tc = await addUser(db, { username: 'tele1', role: 'telecaller', manager: mgr })
const analyst = await addUser(db, { username: 'analyst1', role: 'analyst' })
const gone = await addUser(db, { username: 'gone', role: 'sales', active: false })

console.log('\n# Permission engine')
eq(await as(db, owner, (u) => u.val(`select has_perm('settings')`)), true, 'owner (aal2) has settings')
eq(await as(db, owner, (u) => u.val(`select has_perm('settings')`), { aal: 'aal1' }), false, 'owner WITHOUT MFA has nothing')
eq(await as(db, admin, (u) => u.val(`select has_perm('leads')`), { aal: 'aal1' }), false, 'admin WITHOUT MFA has nothing')
eq(await as(db, sales, (u) => u.val(`select has_perm('leads')`), { aal: 'aal1' }), true, 'sales needs no MFA')
eq(await as(db, sales, (u) => u.val(`select has_perm('settings')`)), false, 'sales has no settings')
eq(await as(db, tc, (u) => u.val(`select has_perm('bookings')`)), false, 'telecaller has no bookings')
eq(await as(db, analyst, (u) => u.val(`select can_write('bookings')`)), false, 'analyst is read-only')
eq(await as(db, gone, (u) => u.val(`select has_perm('leads')`)), false, 'inactive user has nothing')
eq(await as(db, mgr, (u) => u.val(`select my_scope()`)), 'team', 'manager scope = team')
await db.query(`insert into user_overrides values ($1,'bookings',true), ($1,'leads',false)`, [tc])
eq(await as(db, tc, (u) => u.val(`select has_perm('bookings')`)), true, 'override grants a module')
eq(await as(db, tc, (u) => u.val(`select has_perm('leads')`)), false, 'override revokes a module')
await db.query(`delete from user_overrides`)
{
  const me = await as(db, sales, (u) => u.val(`select my_permissions()`))
  ok(me.granted.includes('leads') && !me.granted.includes('settings') && me.role === 'sales', 'my_permissions() lists effective grants')
}

console.log('\n# Lead visibility (RLS)')
const mkLead = (name, ownerId, creator) =>
  one(`insert into leads (name, phone_enc, phone_hint, phone_bidx, owner_id, created_by)
       values ($1, private.enc($2), phone_hint($2), private.bidx($2), $3, $4) returning id`,
    [name, String(9000000000 + Math.floor(Math.random() * 1e8)), ownerId, creator])
const lSales = await mkLead('Lead of sales1', sales, tc)
const lSales2 = await mkLead('Lead of sales2', sales2, sales2)
const names = (uid) => as(db, uid, async (u) => (await u.q(`select name from leads order by name`)).map((r) => r.name))
eq(await names(sales), ['Lead of sales1'], 'sales sees only own lead')
eq(await names(sales2), ['Lead of sales2'], 'other sales sees only theirs')
eq(await names(tc), ['Lead of sales1'], 'telecaller sees the lead they created')
eq(await names(mgr), ['Lead of sales1'], 'manager sees team leads only')
eq((await names(owner)).length, 2, 'owner sees all')
eq(await names(analyst), [], 'analyst (no leads module) sees none')
eq((await as(db, owner, (u) => u.q(`select 1 from leads`), { aal: 'aal1' })).length, 0, 'owner without MFA sees no leads')

console.log('\n# Column protection')
await denied(as(db, sales, (u) => u.q(`select phone_enc from leads`)), 'cannot read ciphertext column')
await denied(as(db, sales, (u) => u.q(`select phone_bidx from leads`)), 'cannot read blind index')
await denied(as(db, sales, (u) => u.q(`update leads set phone_hint = 'x'`)), 'cannot write phone columns directly')
await denied(as(db, sales, (u) => u.q(`insert into leads (name) values ('x')`)), 'cannot insert leads directly (RPC only)')
await denied(as(db, sales, (u) => u.q(`select private.dec('\\x01'::bytea)`)), 'cannot call private.dec')
await denied(as(db, sales, (u) => u.q(`select * from vault.decrypted_secrets`)), 'cannot read the key vault')
await denied(as(db, sales, (u) => u.q(`select failed_logins from profiles`)), 'cannot read login-security columns')
await denied(as(db, sales, (u) => u.q(`update profiles set role = 'owner' where id = $1`, [sales])), 'cannot change own role')
await denied(as(db, sales, (u) => u.q(`insert into user_overrides values ($1,'settings',true)`, [sales])), 'cannot grant self permissions')

console.log('\n# Lead updates')
await as(db, sales, (u) => u.q(`update leads set stage = 'contacted' where id = $1`, [lSales]))
eq(await one(`select stage from leads where id = $1`, [lSales]), 'contacted', 'owner of lead can change stage')
eq(await one(`select count(*)::int from lead_activities where lead_id = $1 and type = 'stage'`, [lSales]), 1, 'stage change is logged to the timeline')
await as(db, sales, (u) => u.q(`update leads set stage = 'booked' where id = $1`, [lSales2]))
eq(await one(`select stage from leads where id = $1`, [lSales2]), 'new', "cannot touch another person's lead (0 rows)")
await denied(as(db, sales, (u) => u.q(`update leads set owner_id = $2 where id = $1`, [lSales, sales2])), 'sales cannot reassign')
await denied(as(db, sales, (u) => u.q(`update leads set stage = 'lost' where id = $1`, [lSales])), 'lost requires a reason')
await as(db, mgr, (u) => u.q(`update leads set owner_id = $2 where id = $1`, [lSales, tc]))
eq(await one(`select owner_id from leads where id = $1`, [lSales]), tc, 'manager can reassign')
eq(await one(`select count(*)::int from notifications where user_id = $1`, [tc]), 1, 'new owner is notified')
await as(db, sales, (u) => u.q(`delete from leads where id = $1`, [lSales]))
eq(await one(`select count(*)::int from leads where id = $1`, [lSales]), 1, 'sales cannot delete leads')

console.log('\n# Login gate & lockout')
const gate = (u, ip) => asService(db, (s) => s.val(`select login_gate($1, $2)`, [u, ip]))
const rec = (u, ip, okk) => asService(db, (s) => s.q(`select login_record($1, $2, $3)`, [u, ip, okk]))
eq(await gate('sales1', '1.1.1.1'), 'ok', 'gate ok initially')
for (let i = 0; i < 5; i++) await rec('sales1', '1.1.1.1', false)
eq(await gate('sales1', '1.1.1.1'), 'locked', 'locked after 5 failures')
eq(await as(db, sales, (u) => u.val(`select has_perm('leads')`)), false, 'locked account loses permissions')
await rec('sales1', '1.1.1.1', true)
eq(await gate('sales1', '1.1.1.1'), 'ok', 'successful login clears the lock')
eq(await gate('gone', '1.1.1.1'), 'inactive', 'inactive account is refused')
eq(await gate('nobody', '1.1.1.1'), 'ok', 'unknown username is not revealed')
for (let i = 0; i < 30; i++) await rec('x' + i, '9.9.9.9', false)
eq(await gate('sales1', '9.9.9.9'), 'ip_blocked', 'IP blocked after 30 failures')
await denied(as(db, sales, (u) => u.q(`select login_gate('a','b')`)), 'browser cannot call login_gate')
await denied(as(db, sales, (u) => u.q(`select svc_revoke_sessions($1)`, [owner])), 'browser cannot call service helpers')

console.log('\n# Audit log')
await denied(db.query(`update audit_log set action = 'x'`), 'audit log cannot be edited')
await denied(db.query(`delete from audit_log`), 'audit log cannot be deleted')
eq(await as(db, sales, async (u) => (await u.q(`select 1 from audit_log`)).length), 0, 'sales cannot read the audit log')
ok((await as(db, owner, async (u) => (await u.q(`select 1 from audit_log`)).length)) > 0, 'owner can read the audit log')

console.log('\n# Employees list')
eq((await as(db, owner, (u) => u.q(`select * from list_employees()`))).length, 8, 'owner lists all employees')
eq((await as(db, mgr, async (u) => (await u.q(`select username from list_employees() order by 1`)).map((r) => r.username))), ['manager1', 'sales1', 'tele1'], 'manager lists self + team')
eq((await as(db, sales, (u) => u.q(`select * from list_employees()`))).length, 0, 'sales cannot list employees')

summary()
