#!/usr/bin/env node
// Writes your Supabase project host into the Content-Security-Policy and switches the
// policy between report-only and enforcing. frontend/vercel.json holds the headers; the
// repo-root customHttp.yml (AWS Amplify Hosting, monorepo format) is regenerated from it so
// both hosts send the same headers.
//
//   node frontend/scripts/set-csp.mjs <project-ref>            # report-only (first few days after go-live)
//   node frontend/scripts/set-csp.mjs <project-ref> --enforce  # after the report-only period is clean
//
// <project-ref> is the id in your Supabase URL: https://<project-ref>.supabase.co
import fs from 'node:fs'

const [ref, flag] = process.argv.slice(2)
if (!/^[a-z0-9]{15,30}$/.test(ref ?? '')) {
  console.error('Usage: node scripts/set-csp.mjs <project-ref> [--enforce]')
  process.exit(1)
}
const host = `${ref}.supabase.co`
const file = new URL('../vercel.json', import.meta.url)
const cfg = JSON.parse(fs.readFileSync(file, 'utf8'))
const headers = cfg.headers[0].headers
const i = headers.findIndex((h) => h.key.startsWith('Content-Security-Policy'))
headers[i] = {
  key: flag === '--enforce' ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only',
  value: headers[i].value.replace(/__SUPABASE_HOST__|[a-z0-9]{15,30}\.supabase\.co/g, host),
}
fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + '\n')
console.log(`vercel.json: ${headers[i].key} now allows ${host}`)

// ---- AWS Amplify Hosting (monorepo: the file sits at the repo root, keyed by appRoot) ----
const q = (s) => `'${s.replace(/'/g, "''")}'`
const block = (pattern, list) =>
  `      - pattern: ${q(pattern)}\n        headers:\n` + list.map((h) => `          - key: ${q(h.key)}\n            value: ${q(h.value)}\n`).join('')
const yml =
  '# Generated by frontend/scripts/set-csp.mjs from frontend/vercel.json. Edit vercel.json, then rerun the script.\n' +
  'applications:\n' +
  '  - appRoot: frontend\n' +
  '    customHeaders:\n' +
  block('**', headers) +
  block('assets/**', cfg.headers.find((h) => h.source === '/assets/(.*)').headers) +
  // the service worker must be re-checked on every visit so updates reach phones
  block('sw.js', [{ key: 'Cache-Control', value: 'no-cache' }])
fs.writeFileSync(new URL('../../customHttp.yml', import.meta.url), yml)
console.log('customHttp.yml (repo root): written for AWS Amplify')
